services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=sei@sei.com
      - PGADMIN_DEFAULT_PASSWORD=sei
    ports:
      - 80:80
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      sei_network:
        ipv4_address: 192.168.20.2

  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=seidb
      - POSTGRES_USER=sei
      - POSTGRES_PASSWORD=sei
      - TZ=America/Sao_Paulo
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      sei_network:
        ipv4_address: 192.168.20.3

  backend:
    build:
      context: ../backend
    environment:
      - NODE_PORT=7001
      - TZ=America/Sao_Paulo
    volumes:
      - ../backend:/code
    ports:
      - 7001:7001
      - 9229:9229
    networks:
      sei_network:
        ipv4_address: 192.168.20.4

  frontend:
    build:
      context: ../frontend
    environment:
      - VUE_PORT=7000
      - TZ=America/Sao_Paulo
    volumes:
      - ../frontend:/code
    ports:
      - 7000:7000
    networks:
      sei_network:
        ipv4_address: 192.168.20.5

networks:
  sei_network:
    driver: bridge
    name: sei_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24